services:
    # image project
    app:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
            args:
              UID: ${LOCAL_UID:-1000} # Fallback to 1000 if not set
              GID: ${LOCAL_GID:-1000} # Fallback to 1000 if not set
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
          - "9000:9000"    
        depends_on: 
          - database
        networks: 
            - laravel
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    database:
      image: mysql:${MYSQL_VERSION:-8.0.22}
      command: [ "--default-authentication-plugin=mysql_native_password" ]
      ports:
        - "${MYSQL_PORT:-3306}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-very_secret}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
        MYSQL_USER: ${MYSQL_USER:-db_user}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      restart: unless-stopped
      networks:
        - laravel
      volumes:
        - db_data:/var/lib/mysql
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE  

volumes:
  db_data:
    driver: local

networks: 
  laravel:
    driver: bridge